%%% run processing steps required to get trialwise high gamma and beta responses from raw fieldtrip data...
%%% .... from all DBSSEQ subs - not-vibration-denoised data
%
% requirements for all subjects before running this batch script:
%   -preprocessing steps through A08 (raw fieldtrip) and B06 (ecog localizations) 
%   -processing step A18 - behavioral annotations - syllable timing, accuracy, and stop responses
%   -manual artifacts file saved - use annotate_manual_ephys_artifacts.m
%   -repos on path: bml, ieeg_ft_funcs_am

clear


% % % % % % op.resp_signal = 'hg'; 
% % % % % % % op.resp_signal = 'beta'; 

op.art_crit = 'G'; 

% op.rereference_method = 'none';
% op.rereference_method = 'CTAR';
op.rereference_method = 'CMR'; % common median... bml_rereference supports this but doesn't list it at the top of the function

op.reref_extreme_trim_percent = 50; % during referencing, percentage of 'extreme' channels in group to trim 

freq_bands_to_extract = {'beta','hg'}; 

% ? not used ? 
op.time_buffer_before_epoch_trial_start = 1; % time buffer in sec before visual onset; ?? gets used in redefine_trial ??

% not using speech-vibration-denoised version of data
op.denoised = 0; 

sublist ={...
     'DM1005';...
     'DM1007';...
     'DM1008';...
     'DM1024';...
     'DM1025';...
     'DM1037';...
     'DM1044';...
     'DM1045';... % NB: reference switched mid-run
       'DM1046';...
       'DM1047';...
     'DM1048';...
     'DM1049';...
% % %      'DM1050';... % poor behavior and ecog localization - don't use
     'DM1051';...
     'DM1052';...
     'DM1054';...
     };

setpaths_dbs_seq()

nsubs = length(sublist);
for isub = 1:nsubs
    thissub = sublist{isub}
    op.sub = thissub;


    close all force

    % load fieldtrip raw and select ephys channels
    set_project_specific_variables(); % get sub-specific info
    load(FT_RAW_FILENAME, 'D')


    %  select only ephys channels selection here
    %%% for smsl, exclude dbs macro and dbs-right channels because we know these weren't recording brain structures of interest during the task
    cfg=[];
    cfg.channel={'ecog_*','dbs_L*'};
    D_sel = ft_selectdata(cfg,D);


    %% filtering
    % load manual artifact - generated by
    manual_artifact_table = bml_annot_read_tsv(PATH_ARTIFACT_MANUAL); 

    % apply manual artifact mask, run cleaning script, highpass filter
    cfg = []; 
    cfg.add_mask = true; % use manual artifact mask
    cfg.mask_table = manual_artifact_table; 
    D_hpf_cleaned = hpf_and_instantaneous_artifact_mask(D,cfg);

    cfg = [];
    [D_notch, cfg_notch] = notch_harmonics_filter(D_hpf_cleaned,cfg);
    save([FT_FILE_PREFIX,'raw-filt_ar-',op.art_crit],'D_notch','cfg_notch')

    %% rereferencing - save output
    % important: set manual artifactual timepoints to nans here, not just zeroes
    % .... so that zeroes don't affect CMR
    % use rereference_ephys here.... either include plotting functions in that or make new plotting function
    %%%% adapt the useful parts of Y:\Documents\Code\ieeg_ft_funcs_am\preprocessing\P09_redefine_trial_common_avg_ref_not_denoised.m
    
    elc_to_reref = electrodes(ismember(electrodes.name,D_sel.label),:);

    % first mask zeroes with nans so they don't affect other channels during rereferencing
    cfg = [];
    cfg.annot = manual_artifact_table; % set manual artifacts to nan
    cfg.complete_trial = false; % full run data, so can't mask individual trials
    cfg.value = NaN; 
    D_notch_nanmask = bml_mask(cfg, D_notch); 

    % do rereerencing
    cfg_reref = [];
    cfg_reref.label = elc_to_reref.name;
    cfg_reref.group = elc_to_reref.connector;
    cfg_reref.method = op.rereference_method; 
    cfg_reref.percent = op.reref_extreme_trim_percent; 
    D_ref = bml_rereference_adapted(cfg_reref,D_notch_nanmask); 
    save([FT_FILE_PREFIX,'raw-filt_ar-',op.art_crit,'_ref-',op.rereference_method],'D_notch','cfg_notch')

    %% get spectral power timecourses
    nbands = length(freq_bands_to_extract);
    for iband = 1:nbands
        thisband = freq_bands_to_extract{iband};
        switch thisband
            case 'beta'
                paramcode = 'F';
            case 'hg'
                paramcode = 'E';
        end
        param = bml_annot_read_tsv([PATH_DBSSEQ_CODE, filesep, 'P08_artifact_criteria_',paramcode,...
            filesep, 'artifact_',paramcode,'_params.tsv']);
        cfg_wavpow = []; 
        cfg_wavpow.param = param; 
        D_wavpow = multifreq_avg_power(cfg_wavpow, D_ref); % get power in band of interest
        cfg_wavpow.thisband = thisband; 
        save([FT_FILE_PREFIX,thisband],'D_wavpow','cfg_wavpow')

    end
    



    % key thing to look at: what does hg and beta power look like on the edges of artifact windows? 

    % definitely need to re-nan the artifact windows after getting hg and beta



end
 