%%% wrapper for plot_resp_timecourse.m specific to the DBS-SEQ project 
 % resp = a single electrode's row from the resp table generated by response_types_seq.m
 % trials = trialtable generated for the subject that the electrode, also generated by response_types_seq.m

function plot_resp_timecourse_seq(resp, trials, op)

% close all

 %% params 
 vardefault('op',struct) ;


field_default('op','sort_cond',[]); % if empty, don't separate traces by trial characteristics
%     field_default('op','sort_cond','learn_con');
    % field_default('op','sort_cond','is_nat');
%     field_default('op','sort_cond','word');
    % field_default('op','sort_cond','vow');
%     field_default('op','sort_cond','word_accuracy');
%     field_default('op','sort_cond','seq_accuracy');

field_default('op','condval_inds_to_plot', []); % plot all vals


field_default('op','plot_go_trials_only',1); % exclude STOP trials from plotting

field_default('op','newfig',1);
field_default('op','smooth_timecourses', 1);
field_default('op','smooth_method','gaussian');
field_default('op','smooth_windowsize',10);
field_default('op','ylimits', []); % use defaults
field_default('op','xlimits',[]);
field_default('op','trace_width',1);

%%%%% trial table varname for times used for time-locking responses
field_default('op','time_align_var','t_prod_on'); % default to speech onset

%%%% trial times to plot 
% the fixed timepoint will be exact (x=0); for other times, we take the avg relative to the fixed point
    % trial-table-varname, line color, text label, L/R side
field_default('op','times_to_plot', {...    
    't_vis_syl_on', [0 0 1],        {'vis','on'},       'L';... 
    't_aud_syl_on', [0.6 0.4 0.1],  {'aud','on'},       'L';...
    't_aud_syl_off',[0.6 0.4 0.1],  {'aud','off'},      'R';...
    't_aud_go_on',  [0 1 0],        {'GO','beep'}       'L';...
    't_prod_on',    [0.5 0.5 0.5],  {'speech','start'}, 'L';...
    't_prod_off',   [0.5 0.5 0.5],  {'speech','end'},    'R';...
    });


%%%% how to find the time length that trials will be cut/padded to be
field_default('op','trial_time_adj_method','median_plus_sd'); % median plus stdev
% field_default('op','trial_time_adj_method','median');
% field_default('op','trial_time_adj_method','max');

field_default('op','leg_pos_adjust',0.22); % move legend position to the left this much

%%%%%% end params
%%
op.times_to_plot = table(op.times_to_plot(:,1), op.times_to_plot(:,2), op.times_to_plot(:,3), op.times_to_plot(:,4), 'VariableNames', {'varname','color','plot_label','line_side'}); 

trials.align_time = trials{:,op.time_align_var}; 

op.sub = resp.sub{1}; 

if op.plot_go_trials_only % exclude stop trials
    go_trial_inds = ~trials.is_stoptrial;
    trials = trials(go_trial_inds,:);
    timecourses_unaligned = resp.timecourse{1}(go_trial_inds); 
elseif ~op.plot_go_trials_only % include both stop and go trials
    timecourses_unaligned = resp.timecourse{1};
end

trials.is_nat = cell(height(trials),1);
    trials.is_nat(strcmp(trials.learn_con,'nat')) = {'native'};
    trials.is_nat(~strcmp(trials.learn_con,'nat')) = {'nonnative'};

if isempty(op.sort_cond) % plot all trials in a single trace
    trial_conds = ones(height(trials),1); 
elseif ~isempty(op.sort_cond)
    trial_conds = trials{:,op.sort_cond}; 
end


 %% sort trials by condition, get average responses + error, plot
 [op, resp_grpd] = plot_resp_timecourse(trials, timecourses_unaligned, trial_conds, op); % from ieeg_ft_funcs_am repo - must be on path

%%

if string(resp.type{1})=="ECOG"
    htitle = title([op.sub, '_', resp.chan{1}, '_area-', resp.HCPMMP1_label_1{1}], 'Interpreter','none');
else
    htitle = title([op.sub, '_', resp.chan{1}, '_area-', resp.DISTAL_label_1{1}], 'Interpreter','none');
end

     
f=get(gca,'Children');

if ~isempty(op.sort_cond)
    nvals_to_plot =  length(op.condval_inds_to_plot); 
    hleg = legend(flipud(f(end-nvals_to_plot+1:end)),resp_grpd.condval{op.condval_inds_to_plot});
    hleg.Position(1) = hleg.Position(1)-op.leg_pos_adjust; % move to the left
end
