%%% run processing steps required to get trialwise high gamma and beta responses from raw fieldtrip data...
%%% .... from all DBSSEQ subs - not-vibration-denoised data
%
% requirements for all subjects before running this batch script:
%   -preprocessing steps through A08 (raw fieldtrip) and B06 (ecog localizations) 
%   -processing step A18 - behavioral annotations - syllable timing, accuracy, and stop responses
%   -manual artifacts file saved - use annotate_manual_ephys_artifacts.m
%   -repos on path: bml, ieeg_ft_funcs_am

clear


op.threshold_method = 'EF';
% op.threshold_method = 'simple_thresh';

op.art_crit = 'G'; %%% maybe change / get rid of this parameter - confusing to have both G (manual art) and E/F (automatic art)

op.skip_to_automatic_artifact_detection = 0; % if true, load pre-made wavpow fieldtrip files, and skip all steps before threshold-based artifact detection

% op.rereference_method = 'none';
% op.rereference_method = 'CTAR';
op.rereference_method = 'CMR'; % common median... bml_rereference supports this but doesn't list it at the top of the function

% op.rereference_method_by_eltype = ...
%     {'ecog',    'CMR';...
%     {'dbs',     '8chan_dbs_bipolar'};

op.reref_extreme_trim_percent = 50; % during referencing, percentage of 'extreme' channels in group to trim 

freq_bands_to_extract = {'beta','hg'}; 
% freq_bands_to_extract = {'beta'}; 
% freq_bands_to_extract = {'hg'}; 

% ? not used ? 
op.time_buffer_before_epoch_trial_start = 1; % time buffer in sec before visual onset; ?? gets used in redefine_trial ??

% not using speech-vibration-denoised version of data
op.denoised = 0; 

sublist ={...
     'DM1005';...
     'DM1007';...
     'DM1008';...
     'DM1024';...
     'DM1025';...
     'DM1037';...
     'DM1044';...
     'DM1045';... % NB: reference switched mid-run
       'DM1046';...
       'DM1047';...
     'DM1048';...
     'DM1049';... % problem during notch filter preproc 2026/7/5 - add back when fixed
% % %      'DM1050';... % poor behavior and ecog localization - don't use
     'DM1051';...
     'DM1052';...
     'DM1054';...
     };

setpaths_dbs_seq()

nsubs = length(sublist);
nbands = length(freq_bands_to_extract);
for isub = 1:nsubs
    thissub = sublist{isub}
    op.sub = thissub;


    close all force
    % load fieldtrip raw and select ephys channels
    set_project_specific_variables(); % get sub-specific info

    if ~op.skip_to_automatic_artifact_detection % do all pipeline steps; don't skip to artifact detection
        load(FT_RAW_FILENAME, 'D')
    
    
        %  select only ephys channels selection here
        %%% for smsl, exclude dbs macro and dbs-right channels because we know these weren't recording brain structures of interest during the task
        cfg=[];
        cfg.channel={'ecog_*','dbs_L*'};
        D_sel = ft_selectdata(cfg,D);
    
    
        %% filtering
        % load manual artifact - generated by annotate_manual_ephys_artifacts.m
        manual_artifact_table = bml_annot_read_tsv(PATH_ARTIFACT_MANUAL); 
    
        % apply manual artifact mask, run cleaning script, highpass filter
        cfg = []; 
        cfg.add_mask = true; % use manual artifact mask
        cfg.mask_table = manual_artifact_table; 
        D_hpf_cleaned = hpf_and_instantaneous_artifact_mask(D_sel,cfg);
    
        fprintf(['\n Notch filtering subject ',thissub,'\n'])
        cfg = [];
        [D_notch, cfg_notch] = notch_harmonics_filter(D_hpf_cleaned,cfg);
        save([FT_FILE_PREFIX,'raw-filt_ar-',op.art_crit],'D_notch','cfg_notch')
    
        %% rereferencing - save output
        elc_to_reref = electrodes(ismember(electrodes.name,D_sel.label),:);
    
        % first mask zeroes with nans so they don't affect other channels during rereferencing
        cfg = [];
        cfg.annot = manual_artifact_table; % set manual artifacts to nan
        cfg.complete_trial = false; % full run data, so can't mask individual trials
        cfg.value = NaN; 
        cfg.label_colname = 'label';
        D_notch_nanmask = bml_mask(cfg, D_notch); 
    
        % do rereferencing ecog
        cfg_ref = [];
        cfg_ref.label = elc_to_reref.name;
        cfg_ref.group = elc_to_reref.connector;
        cfg_ref.method = op.rereference_method; 
        cfg_ref.percent = op.reref_extreme_trim_percent; 
            % ecog
            cfg.channel={'ecog_*'};
            D_sel = ft_selectdata(cfg,D_notch_nanmask);
            D_ref = bml_rereference_adapted(cfg_ref,D_notch_nanmask); 

            % dbs
            cfg.channel={'dbs_L*'};
            D_sel = ft_selectdata(cfg,D_notch_nanmask);
            D_ref = bml_rereference_adapted(cfg_ref,D_notch_nanmask);

        % combine

        % save
        save([FT_FILE_PREFIX,'raw-filt_ar-',op.art_crit,'_ref-',op.rereference_method],'D_ref','cfg_ref')
        
    % % % % % % % % % % % % % % % % %         % Replace from nan to zero
    % % % % % % % % % % % % % % % % %         cfg = [];
    % % % % % % % % % % % % % % % % %         cfg.annot = manual_artifact_table; % set manual artifacts to nan
    % % % % % % % % % % % % % % % % %         cfg.complete_trial = false; % full run data, so can't mask individual trials
    % % % % % % % % % % % % % % % % %         cfg.value = NaN; 
    % % % % % % % % % % % % % % % % %         cfg.label_colname = 'label';
    % % % % % % % % % % % % % % % % %         D_notch_nanmask = bml_mask(cfg, D_ref);
    end 

%% get spectral power timecourses
%     ....... or load them if they are already created and if op.skip_to_automatic_artifact_detection==true
    
    for iband = 1:nbands
        thisband = freq_bands_to_extract{iband};
        wavpow_no_thresh_savename = [FT_FILE_PREFIX,thisband,'_no-thresh-mask']; 
        switch thisband
            case 'beta'
                paramcode = 'F';
            case 'hg'
                paramcode = 'E';
        end
    
    
    
    
        %%%%%%%%%%%%%%%%%%%%%%%%%   LOAD OR COMPUTE WAV POWER TIMECOURSES   %%%%%%%%%%%%%%%%%%%%%%%%%
        %%% using 'param' as a hack to maintain compatibility w/ Triplet and backward compatibility:  ...
        ........ - load artifact parameters, but set all chantypes to have same params
        artparam = bml_annot_read_tsv([PATH_DBSSEQ_CODE, filesep, 'P08_artifact_criteria_',paramcode,...
            filesep, 'artifact_',paramcode,'_params.tsv']);
            artparam = artparam(1,:); 
            artparam.name{1} = 'all';
            artparam.electrode_type{1} = '*'; % include all elc types
    
        if ~ op.skip_to_automatic_artifact_detection % compute wavpow timecourse, save over prior version if it exists
            cfg_wavpow = []; 
            cfg_wavpow.param = artparam;  
            D_wavpow_no_thresh_mask = multifreq_avg_power(cfg_wavpow, D_ref); % get power in band of interest
            cfg_wavpow.thisband = thisband; 
            save(wavpow_no_thresh_savename,'D_wavpow_no_thresh_mask','cfg_wavpow')
    
        % option below assumes that prior steps have already been run and that we don't want to rerun them
        %     the prior steps take a long time, so the purpose of this option is to quickly try out different thresh artifact parameters
        ......... without having to rerun the exact same filter/ref/wavpow steps              
        elseif op.skip_to_automatic_artifact_detection
            load(wavpow_no_thresh_savename,'D_wavpow_no_thresh_mask','cfg_wavpow')   
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    
    
    
    
        %%%%%%%%%%%%%%%%%%%%% COMPUTE THRESHOLD-BASED ARTIFACT MASK - E/F or simple_thresh/Fsimple %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %    save threshold artifact mask in same format and location as artifact manual (separate file from manual mask)
        %    set timepoints in wavpow that this mask finds to nan
    
        cfg_thresh_art = []; 
        cfg_thresh_art.freqband = thisband; 
        cfg_thresh_art.threshold_method = op.threshold_method; 
        cfg_thresh_art.sub = op.sub; 
        cfg_thresh_art.electrodes = electrodes; 
        cfg_thresh_art.artparam = artparam;    clear artparam
        [D_wavpow, thresh_artifact_table, cfg_thresh_art_out] = apply_threshold_artifact_mask(D_wavpow_no_thresh_mask,cfg_thresh_art);
    
        % expand mask here - not implemented yet 
        cfg_expand_art = [];
        cfg_expand_art.win_buffer_sample = 100;
        D_wavpow = expand_artifact_mask(D_wavpow, cfg_expand_art);
        % key thing to look at: what does hg and beta power look like on the edges of artifact windows? 
    
        art_thresh_table_savename = [PATH_ANNOT, filesep, 'sub-', op.sub, '_ses-' SESSION '_task-' TASK, '_artifact-crit-',cfg_thresh_art_out.paramcode,'.tsv']; 
        writetable(thresh_artifact_table, art_thresh_table_savename, 'delimiter','\t', 'FileType','text'); % save threshold-based artifact mask
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    


        % save wavpow for this band after applying the threshold-based bask 
        wavpow_savename = [FT_FILE_PREFIX, thisband];
        save(wavpow_savename,'D_wavpow','op','cfg_wavpow','thresh_artifact_table','cfg_thresh_art')

    end

end



function [D_wavpow, thresh_artifact_table, cfg_thresh_art_out] = apply_threshold_artifact_mask(D_in,cfg_thresh_art_in)
    cfg_thresh_art_out = cfg_thresh_art_in; 
    switch cfg_thresh_art_in.threshold_method
            case 'EF' % BML artifact detection method
                switch cfg_thresh_art_in.freqband
                    case 'beta'
                        cfg_thresh_art_out.paramcode = 'F';
                    case 'hg'
                        cfg_thresh_art_out.paramcode = 'E';
                end

                [D_wavpow, thresh_artifact_table] = P08A09_detect_artifact(D_in,cfg_thresh_art_in);
            case 'simple_thresh' %%% simplified threshold method - just look for timepoints above a certain threshold - not implemented yet
                cfg_thresh_art_out.paramcode = 'simple_thresh';
                cfg = []; cfg.threshold = 2;
                [D_wavpow, ~] = threshold_artifact_detection(D_in, cfg);
     end
        
end
 